// Auto-generated for leverage template - DO NOT EDIT
// Generated by create-app-direct.js
// Chain ID: 11155931 (RISE Testnet)

// Import ABIs
import LeverageTradingABI from './abi/LeverageTrading.json';
import PriceOracleABI from './abi/PriceOracleV2.json';
import ERC20ABI from './abi/ERC20.json';

export const contracts = {
  LeverageTrading: {
    address: '0xec472935c006751295453aa55Dd7A3518e626Eb8' as const,
    deploymentTxHash: '',
    blockNumber: 0,
    abi: LeverageTradingABI
  },
  USDC: {
    address: '0x8A93d247134d91e0de6f96547cB0204e5BE8e5D8' as const,
    
    abi: ERC20ABI
  },
  PriceOracle: {
    address: '0x5A569Ad19272Afa97103fD4DbadF33B2FcbaA175' as const,
    
    abi: PriceOracleABI
  }
} as const;

// Type exports
export type ContractName = keyof typeof contracts;
export type Contracts = typeof contracts;

// Helper functions
export function getContract<T extends ContractName>(name: T): Contracts[T] {
  return contracts[name];
}

export function getContractAddress(name: ContractName): string {
  return contracts[name].address;
}

export function getContractABI(name: ContractName) {
  return contracts[name].abi;
}

// Re-export primary contract for convenience
export const LEVERAGETRADING_ADDRESS = '0xec472935c006751295453aa55Dd7A3518e626Eb8' as const;
export const LEVERAGETRADING_ABI = LeverageTradingABI;

// Re-export USDC and Oracle addresses
export const USDC_ADDRESS = '0x8A93d247134d91e0de6f96547cB0204e5BE8e5D8' as const;
export const USDC_ABI = ERC20ABI;
export const PRICEORACLE_ADDRESS = '0x5A569Ad19272Afa97103fD4DbadF33B2FcbaA175' as const;
